### ISSUE TITLE
Release transforms as NuGet package

### ISSUE THREAD

**Issue by chrischu** [appharbor/appharbor-transformtester#6]
It would be tremendously useful if the Merge/MergeBefore transforms were available via NuGet package so that I can use them in my own projects.

**Comment by chrischu** [comment]
Nevermind I just realized that there is a new XDT-transform called "InsertIfMissing" :).

**Comment by dagilleland** [comment]
@chrischu - Would love to know where you are finding the "InsertIfMissing". The ["fully syntax guide" documentation on MSDN](https://msdn.microsoft.com/en-us/library/dd465326.aspx) is not so complete....

**Comment by chrischu** [comment]
@dagilleland Yes, unfortunately the Microsoft docs went aren't always kept up to date. A little bit of googling goes a long way though, fire example it leads to this: https://stackoverflow.com/questions/15102834/web-config-transforms-insert-if-not-exists
